### ISSUE TITLE
top1 and top5 results are 0 for LM_512D_30_iter_60000.caffemodel

### ISSUE THREAD

**Issue by DoubleKing0625** [MahdiHajibabaei/unified-embedding#3]
Hi, when I run test_ident.py using provided LM_512D_30_iter_60000.caffemodel, I got result 0 for top1 and top5.
Probably the reason is caffe env. Because I saw that there exists many differences in the realization of layers between caffe sphereface and AM-softmax.
Could you indicate which caffe env is used actually?

**Comment by MahdiHajibabaei** [comment]
Hi,

This happens because collectors of the dataset at University of Oxford have changed the dataset and its split. In result, the alphabetical order of the folders (named after identities) that were used to allocate classes in output is no longer valid. In order to use the pipeline for identification, you have to train a model from scratch. For verification, you have to figure out the identities that are reserved for testing and train a model from scratch using recordings from the rest of identities.

**Comment by DoubleKing0625** [comment]
Thanks~ This works.
